{"name": "test_incorrect_password", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('self', <FixtureRequest for <Function test_incorrect_password>>)", "trace": "file C:\\Users\\User\\PycharmProjects\\shop_tests_allure\\tests\\login_form\\test_login_form.py, line 51\n  @allure.description(\"login with incorrect password\")\n  @allure.severity(severity_level=\"NORMAL\")\n  def test_incorrect_password(self):\nE       fixture 'self' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, set_up, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\User\\PycharmProjects\\shop_tests_allure\\tests\\login_form\\test_login_form.py:51"}, "description": "login with incorrect password", "start": 1615729404676, "stop": 1615729404676, "uuid": "02faffaf-949b-46e2-937f-ce96d38101ce", "historyId": "75c28363b8398ae463e9934f431b59c7", "testCaseId": "d59001ef0d751e8aa22ebde1f54ae55b", "fullName": "test_login_form#test_incorrect_password", "labels": [{"name": "severity", "value": "NORMAL"}, {"name": "suite", "value": "test_login_form"}, {"name": "host", "value": "User-ПК"}, {"name": "thread", "value": "7196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_form"}]}