{"uuid": "955a1acf-5d62-4b1d-a8f4-46bbc488be30", "children": ["8a09d1e9-3130-4143-af01-5b22c412c11b"], "befores": [{"name": "set_up", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\User\\PycharmProjects\\shop_tests_allure\\tests\\login_form\\test_login_form.py\", line 12, in set_up\n    driver = webdriver.Chrome(executable_path=constants.path_google_chrome)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\urllib3\\poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n    httplib_response = self._make_request(\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n    httplib_response = conn.getresponse()\n  File \"C:\\Users\\User\\anaconda3\\lib\\http\\client.py\", line 1332, in getresponse\n    response.begin()\n  File \"C:\\Users\\User\\anaconda3\\lib\\http\\client.py\", line 303, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\User\\anaconda3\\lib\\http\\client.py\", line 264, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\User\\anaconda3\\lib\\socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1615731158625, "stop": 1615731159266}], "start": 1615731158625, "stop": 1615731159918}